### ISSUE TITLE
Can you help? This doesn't seem to be published or not working?

### ISSUE THREAD

**Issue by niftylettuce** [lbeeon/smtp-benchmark#2]
I tried to clone repo and run this but it doesn't work:

```sh
❯ go run main.go -h 127.0.0.1:25
# command-line-arguments
./main.go:161:14: undefined: getEmlMail
./main.go:166:14: undefined: getDefaultMail
./main.go:179:2: undefined: dumpMail
```

**Comment by lbeeon** [comment]
You can try `go install github.com/lbeeon/smtp-benchmark`.
Execute it in a binary way, or `go run *.go -h 127.0.0.1:25`

**Comment by niftylettuce** [comment]
that doesn't do anything

**Comment by lbeeon** [comment]
It will be good if you can provide more information like a snapshot.
